# Generated by Django 2.1.3 on 2019-01-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0002_question_qotw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qotw',
        ),
    ]
