# Generated by Django 2.1.3 on 2019-01-04 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ciscoapp', '0004_question_qotw'),
    ]

    operations = [
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(db_column='points', default=0)),
            ],
            options={
                'verbose_name_plural': 'points',
                'db_table': 'point',
            },
        ),
        migrations.RemoveField(
            model_name='login',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='points',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciscoapp.login'),
        ),
    ]
